name: ktlint

on:
  pull_request:
    paths:
      - "**/*.kt"
# Manual trigger
  workflow_dispatch:
    inputs:

jobs:
   ktlint:
     runs-on: ubuntu-latest

     steps:
       - name: "checkout"
         uses: actions/checkout@v4

       - name: "ktlint"
         uses: "vroy/gha-kotlin-linter@v4"
